### ISSUE TITLE
Hammer only mines 1 block

### ISSUE THREAD

**Issue by GrownUpBaby** [ekul6547/LapisCore-Datapacks#5]
I made a diamond hammer but it only mines a single block. The other tools work the way they are intended besides the hammer.

**Comment by ekul6547** [comment]
Sorry for the later reply.
I'm working on a new version of Tinkery, which should come out soon.
Try making sure LapisCore is updated to the latest version.
I don't have much information to go off of, but so far, I have been unable to identify the problem.

**Comment by xannor** [comment]
I noticed this bug as well, but it seems to only happen when I am below chunk z-15, above this it works fine. I can even sit at the edge of the chunk, highlight something, move into chunk z-16 and the highlight dissappears. the x axis does not seem to be an issue though, only the z. I am playing in 1.14.2 and have a few other datapacks loaded. I also did a clear cache and optimize but that did nt change anything.

Update:
I have had it randomly happen above z-15, it is consistent in the spots it does not work but not consistent with it being a whole chunk. Below z-15 it does not work, have not tried a large negative z yet but at least till z-50 I have not gotten it to work. I also have not tried using just these packs to see if it is a conflict. The only pack I have that I believe could cause a conflict is ZCBM Viewminer.

**Comment by ekul6547** [comment]
I just tested it, and yes, outside a radius It seems to stop working, although it was X axis for me, not Z.
I have just identified the problem, and released a hotfix.
Please download both the v0.1.1 for Tinkery Hammers, **AND** the new hotfix for LapisCore: v0.4.1.
The problem was I was teleporting an entity to 0 0 0 just before hammers uses it, but that meant that the datapacks couldn't find it (even though 0 0 is loaded, need to look into this more).
So I just removed the teleport code, and all seemed to be working for me. I'd like your feedback to see if it works please.

**Comment by ekul6547** [comment]
> I noticed this bug as well, but it seems to only happen when I am below chunk z-15, above this it works fine. I can even sit at the edge of the chunk, highlight something, move into chunk z-16 and the highlight dissappears. the x axis does not seem to be an issue though, only the z. I am playing in 1.14.2 and have a few other datapacks loaded. I also did a clear cache and optimize but that did nt change anything.
> 
> Update:
> I have had it randomly happen above z-15, it is consistent in the spots it does not work but not consistent with it being a whole chunk. Below z-15 it does not work, have not tried a large negative z yet but at least till z-50 I have not gotten it to work. I also have not tried using just these packs to see if it is a conflict. The only pack I have that I believe could cause a conflict is ZCBM Viewminer.

I just tested it, and yes, outside a radius It seems to stop working, although it was X axis for me, not Z.
I have just identified the problem, and released a hotfix.
Please download both the v0.1.1 for Tinkery Hammers, AND the new hotfix for LapisCore: v0.4.1.
The problem was I was teleporting an entity to 0 0 0 just before hammers uses it, but that meant that the datapacks couldn't find it (even though 0 0 is loaded, need to look into this more).
So I just removed the teleport code, and all seemed to be working for me. I'd like your feedback to see if it works please.

**Comment by xannor** [comment]
Got a chance to test it out and it seems to be working in places it didn't before. I also do not hear a splashing sound when near water. Targeting under water still seems to be an issue, but that is minor.
